# Generated by Django 5.1.7 on 2025-03-20 09:59

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='cid')),
                ('name', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Category',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='QtyType',
            fields=[
                ('qid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='qid')),
                ('name', models.CharField(max_length=45)),
                ('value', models.CharField(max_length=45)),
            ],
            options={
                'verbose_name_plural': 'Qty_Type',
                'db_table': 'qty_type',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='uid')),
                ('name', models.CharField(max_length=45)),
                ('provider', models.CharField(choices=[('1', 'Customer'), ('2', 'Retailer'), ('3', 'Vendor'), ('4', 'Admin')], max_length=45)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('pwd', models.CharField(default='', max_length=15, validators=[django.core.validators.MinLengthValidator(6)])),
                ('phone_number', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(8)])),
                ('fcm_token', models.TextField(blank=True, max_length=300, null=True)),
                ('device_token', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('sign_in_token', models.CharField(default='', max_length=40)),
                ('status', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'User',
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('scid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='scid')),
                ('name', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
            ],
            options={
                'verbose_name_plural': 'Sub_Category',
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('oid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='oid')),
                ('name', models.CharField(max_length=45)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('status', models.BooleanField(default=True)),
                ('last_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'Offers',
                'db_table': 'offers',
            },
        ),
    ]
