# Generated by Django 5.1.7 on 2025-03-20 12:15

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('bid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='bid')),
                ('title', models.CharField(max_length=45)),
                ('qty', models.CharField(max_length=45)),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('qty_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.qtytype')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'Borrow',
                'db_table': 'borrow',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('eid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='eid')),
                ('title', models.CharField(max_length=45)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'Expense',
                'db_table': 'expense',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('nid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='nid')),
                ('name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=0)),
                ('total_qty_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_date', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('qty_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.qtytype')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'Inventory',
                'db_table': 'inventory',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('nid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='nid')),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=300)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'Notification',
                'db_table': 'notification',
            },
        ),
    ]
