# Generated by Django 5.1.7 on 2025-03-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_user_device_status_alter_offers_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='image',
            field=models.ImageField(blank=True, upload_to='notifications/'),
        ),
    ]
