# Generated by Django 5.1.7 on 2025-04-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_user_shop_name_alter_notification_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='device_status',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.CharField(default='SELF', max_length=45),
        ),
    ]
