# Generated by Django 5.1.7 on 2025-04-17 04:20

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_category_image_subcategory_brand_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='description',
        ),
        migrations.CreateModel(
            name='CategoryMap',
            fields=[
                ('cmid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='cmid')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_to', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.category')),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'CategoryMap',
                'db_table': 'CategoryMap',
            },
        ),
        migrations.CreateModel(
            name='SubCategoryMap',
            fields=[
                ('scmid', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='scmid')),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('sub_category_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.subcategory')),
                ('user_id', models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apis.user')),
            ],
            options={
                'verbose_name_plural': 'SubCategoryMap',
                'db_table': 'SubCategoryMap',
            },
        ),
    ]
